name: simplified_sd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - controlnet-aux==0.0.10
      - datasets==4.1.1
      - diffusers==0.35.1
      - dill==0.4.0
      - einops==0.8.1
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - grpcio==1.75.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - jinja2==3.1.4
      - lazy-loader==0.4
      - markdown==3.9
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.2
      - peft==0.17.0
      - pillow==11.0.0
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - pyarrow==21.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - simsimd==6.5.3
      - six==1.17.0
      - stringzilla==4.0.14
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.5.10
      - timm==1.0.20
      - tokenizers==0.22.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.56.1
      - triton==3.3.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - xformers==0.0.31
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
